server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://221.168.32.248:3306/trade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gmc
    password: Gmc@1234!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    generate-ddl: true
    properties:
      hibernate.format_sql: true
      globally_quoted_identifiers: true

  jackson:
    serialization:
      fail-on-empty-beans: false
